outputs = (
    "I was really pulling for {0} too. Oh well!",
    "I guess {0} really wasn't a pea-brain!",
    "Ahhh now that {0} is gone we can quit playing! No? Ok fine!",
    "All things considered, I think we can all agree that {0} was a straight shooter.",
    "Noooooooo. Not {0}!",
    "I call dibs on {0}'s stuff. Too soon?",
    "Well I guess {0} and I won't be doing that thing anymore...",
    "Here lies {0}. A loser.",
    "RIP {0}.",
    "I kinda hated {0} anyway.",
    "Hey {0}! I'm back with your snacks! Oh...",
    "{0}, you're like modern art now!",
    "Called it!",
    "Really guys? {0}'s dead? Well this server officially blows now.",
    "Does this mean I don't have to return the book {0} lent me?",
    "Oh come on! Now {0}'s blood is all over my server!",
    "I'll always remember {0}...",
    "Well at least {0} stopped crying.",
    "Don't look at me. You guys are cleaning up {0}.",
    "What I'm not crying. *sniff*",
    "I TOLD YOU, YOU COULD DO IT!",
    "Well I'm sure someone will miss you, {0}.",
    "Never forget. {0}.",
    "Yeah. Real smart guys. Just kill off all the fun people.",
    "I think I got some splatter on me. Gross",
    "I told you it would blow your mind!",
    "Well this is fun...",
    "I go to get popcorn and you all start without me. Rude.",
    "Oh God. Just before {0} pulled the trigger they shit their pants.",
    "I guess I'll dig this hole a little bigger...",
    "10/10 would watch {0} blow their brains out again.",
    "Well I hope {0} has life insurance...",
    "See you in the next life, {0}",
    "AND THEIR OFF! Oh... wrong game.",
    "1-800-273-8255",
    "I don't know how, but I think {1} cheated.",
    "{0} always said they wanted to go out with a bang.",
    "So don't sing *another one bites the dust*?",
    "I can't tell if the smile on {1}'s face is relief or insanity.",
    "Oh stop crying {1}. {0} knew what they were getting into.",
    "So that's what a human looks like on the inside!",
    "My condolences {1}. I know you were *so* close to {0}.",
    "GOD NO. PLEASE NO. PLEASE GOD NO. NOOOOOOOOOOOOOOOOOOOOOOO!",
    "BOOM HEADSHOT!",
    "*You miss 100% of the shots you don't take.*",
    "The whole world is going to shit, and you guys are just killing yourselves. But what do I "
    "know. I'm just a bot.",
    "Quit smiling {1}. Its only a matter of time.",
    "I think {1} is laughing a little *too* hard.",
    "{0} was planning to take the server from {2} anyway.",
    "I like how {2} sits in their ivory tower while the rest of you kill yourselves.",
    "It was about time we thinned the herd.",
    "Humans killing each other... This is the best day of my life. :robot:",
    "Is it weird that I'm suddenly hungry now?",
    "{1}, stop poking {0}'s body. Have some respect!",
    "Win some, you lose some.",
    "Don't act like you didn't enjoy that, {1}!",
    "Is it weird that I wish {1} was dead instead?",
    "Oh real great. {0} dies and I'm still stuck with {1}. Real. Great.",
    "Are you eating cheetos? Have some respect {1}! {0} just died!",
)
